export const Icons = {
  Home: 'lucide:home',
  Library: 'lucide:library-big',
  Settings: 'lucide:settings',
  User: 'lucide:user',
  X: 'lucide:x',
  Author: 'lucide:book-user',
  Quote: 'lucide:quote',
  Calendar: 'lucide:calendar-fold',
  MoreHorizontal: 'lucide:more-horizontal',
  Trash: 'lucide:trash-2',
  Edit: 'lucide:edit-2',
  Copy: 'lucide:copy',
  CopyCheck: 'lucide:copy-check',
  CopyFailed: 'lucide:copy-x',
  Refresh: 'lucide:refresh-ccw',
  ArrowLeft: 'lucide:arrow-left',
  Check: 'lucide:check',
  Alert: 'lucide:triangle-alert',
  BookAlert: 'lucide:book-alert',
  Upload: 'lucide:upload',
  CircleCheck: 'lucide:circle-check-big',
  Location: 'lucide:text-search',
  Book: 'lucide:book-a',
  BookDashed: 'lucide:book-dashed',
  BookCheck: 'lucide:book-check',
  Restore: 'lucide:database-backup',
};
